# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from birdie.daemon import daemon_pb2 as daemon__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in daemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DaemonServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/daemon.DaemonService/Login',
                request_serializer=daemon__pb2.LoginRequest.SerializeToString,
                response_deserializer=daemon__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.WaitSSOLogin = channel.unary_unary(
                '/daemon.DaemonService/WaitSSOLogin',
                request_serializer=daemon__pb2.WaitSSOLoginRequest.SerializeToString,
                response_deserializer=daemon__pb2.WaitSSOLoginResponse.FromString,
                _registered_method=True)
        self.Up = channel.unary_unary(
                '/daemon.DaemonService/Up',
                request_serializer=daemon__pb2.UpRequest.SerializeToString,
                response_deserializer=daemon__pb2.UpResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/daemon.DaemonService/Status',
                request_serializer=daemon__pb2.StatusRequest.SerializeToString,
                response_deserializer=daemon__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Down = channel.unary_unary(
                '/daemon.DaemonService/Down',
                request_serializer=daemon__pb2.DownRequest.SerializeToString,
                response_deserializer=daemon__pb2.DownResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/daemon.DaemonService/GetConfig',
                request_serializer=daemon__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=daemon__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.ListNetworks = channel.unary_unary(
                '/daemon.DaemonService/ListNetworks',
                request_serializer=daemon__pb2.ListNetworksRequest.SerializeToString,
                response_deserializer=daemon__pb2.ListNetworksResponse.FromString,
                _registered_method=True)
        self.SelectNetworks = channel.unary_unary(
                '/daemon.DaemonService/SelectNetworks',
                request_serializer=daemon__pb2.SelectNetworksRequest.SerializeToString,
                response_deserializer=daemon__pb2.SelectNetworksResponse.FromString,
                _registered_method=True)
        self.DeselectNetworks = channel.unary_unary(
                '/daemon.DaemonService/DeselectNetworks',
                request_serializer=daemon__pb2.SelectNetworksRequest.SerializeToString,
                response_deserializer=daemon__pb2.SelectNetworksResponse.FromString,
                _registered_method=True)
        self.ForwardingRules = channel.unary_unary(
                '/daemon.DaemonService/ForwardingRules',
                request_serializer=daemon__pb2.EmptyRequest.SerializeToString,
                response_deserializer=daemon__pb2.ForwardingRulesResponse.FromString,
                _registered_method=True)
        self.DebugBundle = channel.unary_unary(
                '/daemon.DaemonService/DebugBundle',
                request_serializer=daemon__pb2.DebugBundleRequest.SerializeToString,
                response_deserializer=daemon__pb2.DebugBundleResponse.FromString,
                _registered_method=True)
        self.GetLogLevel = channel.unary_unary(
                '/daemon.DaemonService/GetLogLevel',
                request_serializer=daemon__pb2.GetLogLevelRequest.SerializeToString,
                response_deserializer=daemon__pb2.GetLogLevelResponse.FromString,
                _registered_method=True)
        self.SetLogLevel = channel.unary_unary(
                '/daemon.DaemonService/SetLogLevel',
                request_serializer=daemon__pb2.SetLogLevelRequest.SerializeToString,
                response_deserializer=daemon__pb2.SetLogLevelResponse.FromString,
                _registered_method=True)
        self.ListStates = channel.unary_unary(
                '/daemon.DaemonService/ListStates',
                request_serializer=daemon__pb2.ListStatesRequest.SerializeToString,
                response_deserializer=daemon__pb2.ListStatesResponse.FromString,
                _registered_method=True)
        self.CleanState = channel.unary_unary(
                '/daemon.DaemonService/CleanState',
                request_serializer=daemon__pb2.CleanStateRequest.SerializeToString,
                response_deserializer=daemon__pb2.CleanStateResponse.FromString,
                _registered_method=True)
        self.DeleteState = channel.unary_unary(
                '/daemon.DaemonService/DeleteState',
                request_serializer=daemon__pb2.DeleteStateRequest.SerializeToString,
                response_deserializer=daemon__pb2.DeleteStateResponse.FromString,
                _registered_method=True)
        self.SetSyncResponsePersistence = channel.unary_unary(
                '/daemon.DaemonService/SetSyncResponsePersistence',
                request_serializer=daemon__pb2.SetSyncResponsePersistenceRequest.SerializeToString,
                response_deserializer=daemon__pb2.SetSyncResponsePersistenceResponse.FromString,
                _registered_method=True)
        self.TracePacket = channel.unary_unary(
                '/daemon.DaemonService/TracePacket',
                request_serializer=daemon__pb2.TracePacketRequest.SerializeToString,
                response_deserializer=daemon__pb2.TracePacketResponse.FromString,
                _registered_method=True)
        self.StartCapture = channel.unary_stream(
                '/daemon.DaemonService/StartCapture',
                request_serializer=daemon__pb2.StartCaptureRequest.SerializeToString,
                response_deserializer=daemon__pb2.CapturePacket.FromString,
                _registered_method=True)
        self.StartBundleCapture = channel.unary_unary(
                '/daemon.DaemonService/StartBundleCapture',
                request_serializer=daemon__pb2.StartBundleCaptureRequest.SerializeToString,
                response_deserializer=daemon__pb2.StartBundleCaptureResponse.FromString,
                _registered_method=True)
        self.StopBundleCapture = channel.unary_unary(
                '/daemon.DaemonService/StopBundleCapture',
                request_serializer=daemon__pb2.StopBundleCaptureRequest.SerializeToString,
                response_deserializer=daemon__pb2.StopBundleCaptureResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/daemon.DaemonService/SubscribeEvents',
                request_serializer=daemon__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=daemon__pb2.SystemEvent.FromString,
                _registered_method=True)
        self.GetEvents = channel.unary_unary(
                '/daemon.DaemonService/GetEvents',
                request_serializer=daemon__pb2.GetEventsRequest.SerializeToString,
                response_deserializer=daemon__pb2.GetEventsResponse.FromString,
                _registered_method=True)
        self.SwitchProfile = channel.unary_unary(
                '/daemon.DaemonService/SwitchProfile',
                request_serializer=daemon__pb2.SwitchProfileRequest.SerializeToString,
                response_deserializer=daemon__pb2.SwitchProfileResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/daemon.DaemonService/SetConfig',
                request_serializer=daemon__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=daemon__pb2.SetConfigResponse.FromString,
                _registered_method=True)
        self.AddProfile = channel.unary_unary(
                '/daemon.DaemonService/AddProfile',
                request_serializer=daemon__pb2.AddProfileRequest.SerializeToString,
                response_deserializer=daemon__pb2.AddProfileResponse.FromString,
                _registered_method=True)
        self.RenameProfile = channel.unary_unary(
                '/daemon.DaemonService/RenameProfile',
                request_serializer=daemon__pb2.RenameProfileRequest.SerializeToString,
                response_deserializer=daemon__pb2.RenameProfileResponse.FromString,
                _registered_method=True)
        self.RemoveProfile = channel.unary_unary(
                '/daemon.DaemonService/RemoveProfile',
                request_serializer=daemon__pb2.RemoveProfileRequest.SerializeToString,
                response_deserializer=daemon__pb2.RemoveProfileResponse.FromString,
                _registered_method=True)
        self.ListProfiles = channel.unary_unary(
                '/daemon.DaemonService/ListProfiles',
                request_serializer=daemon__pb2.ListProfilesRequest.SerializeToString,
                response_deserializer=daemon__pb2.ListProfilesResponse.FromString,
                _registered_method=True)
        self.GetActiveProfile = channel.unary_unary(
                '/daemon.DaemonService/GetActiveProfile',
                request_serializer=daemon__pb2.GetActiveProfileRequest.SerializeToString,
                response_deserializer=daemon__pb2.GetActiveProfileResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/daemon.DaemonService/Logout',
                request_serializer=daemon__pb2.LogoutRequest.SerializeToString,
                response_deserializer=daemon__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.GetFeatures = channel.unary_unary(
                '/daemon.DaemonService/GetFeatures',
                request_serializer=daemon__pb2.GetFeaturesRequest.SerializeToString,
                response_deserializer=daemon__pb2.GetFeaturesResponse.FromString,
                _registered_method=True)
        self.TriggerUpdate = channel.unary_unary(
                '/daemon.DaemonService/TriggerUpdate',
                request_serializer=daemon__pb2.TriggerUpdateRequest.SerializeToString,
                response_deserializer=daemon__pb2.TriggerUpdateResponse.FromString,
                _registered_method=True)
        self.GetPeerSSHHostKey = channel.unary_unary(
                '/daemon.DaemonService/GetPeerSSHHostKey',
                request_serializer=daemon__pb2.GetPeerSSHHostKeyRequest.SerializeToString,
                response_deserializer=daemon__pb2.GetPeerSSHHostKeyResponse.FromString,
                _registered_method=True)
        self.RequestJWTAuth = channel.unary_unary(
                '/daemon.DaemonService/RequestJWTAuth',
                request_serializer=daemon__pb2.RequestJWTAuthRequest.SerializeToString,
                response_deserializer=daemon__pb2.RequestJWTAuthResponse.FromString,
                _registered_method=True)
        self.WaitJWTToken = channel.unary_unary(
                '/daemon.DaemonService/WaitJWTToken',
                request_serializer=daemon__pb2.WaitJWTTokenRequest.SerializeToString,
                response_deserializer=daemon__pb2.WaitJWTTokenResponse.FromString,
                _registered_method=True)
        self.StartCPUProfile = channel.unary_unary(
                '/daemon.DaemonService/StartCPUProfile',
                request_serializer=daemon__pb2.StartCPUProfileRequest.SerializeToString,
                response_deserializer=daemon__pb2.StartCPUProfileResponse.FromString,
                _registered_method=True)
        self.StopCPUProfile = channel.unary_unary(
                '/daemon.DaemonService/StopCPUProfile',
                request_serializer=daemon__pb2.StopCPUProfileRequest.SerializeToString,
                response_deserializer=daemon__pb2.StopCPUProfileResponse.FromString,
                _registered_method=True)
        self.GetInstallerResult = channel.unary_unary(
                '/daemon.DaemonService/GetInstallerResult',
                request_serializer=daemon__pb2.InstallerResultRequest.SerializeToString,
                response_deserializer=daemon__pb2.InstallerResultResponse.FromString,
                _registered_method=True)
        self.ExposeService = channel.unary_stream(
                '/daemon.DaemonService/ExposeService',
                request_serializer=daemon__pb2.ExposeServiceRequest.SerializeToString,
                response_deserializer=daemon__pb2.ExposeServiceEvent.FromString,
                _registered_method=True)


class DaemonServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Login uses setup key to prepare configuration for the daemon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitSSOLogin(self, request, context):
        """WaitSSOLogin uses the userCode to validate the TokenInfo and
        waits for the user to continue with the login on a browser
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Up(self, request, context):
        """Up starts engine work in the daemon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Status of the service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Down(self, request, context):
        """Down stops engine work in the daemon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """GetConfig of the daemon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNetworks(self, request, context):
        """List available networks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectNetworks(self, request, context):
        """Select specific routes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeselectNetworks(self, request, context):
        """Deselect specific routes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardingRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DebugBundle(self, request, context):
        """DebugBundle creates a debug bundle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogLevel(self, request, context):
        """GetLogLevel gets the log level of the daemon
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLogLevel(self, request, context):
        """SetLogLevel sets the log level of the daemon
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStates(self, request, context):
        """List all states
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanState(self, request, context):
        """Clean specific state or all states
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteState(self, request, context):
        """Delete specific state or all states
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSyncResponsePersistence(self, request, context):
        """SetSyncResponsePersistence enables or disables sync response persistence
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TracePacket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCapture(self, request, context):
        """StartCapture begins streaming packet capture on the WireGuard interface.
        Requires --enable-capture set at service install/reconfigure time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartBundleCapture(self, request, context):
        """StartBundleCapture begins capturing packets to a server-side temp file
        for inclusion in the next debug bundle. Auto-stops after the given timeout.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopBundleCapture(self, request, context):
        """StopBundleCapture stops the running bundle capture. Idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logout disconnects from the network and deletes the peer from the management server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerUpdate(self, request, context):
        """TriggerUpdate initiates installation of the pending enforced version.
        Called when the user clicks the install button in the UI (Mode 2 / enforced update).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeerSSHHostKey(self, request, context):
        """GetPeerSSHHostKey retrieves SSH host key for a specific peer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestJWTAuth(self, request, context):
        """RequestJWTAuth initiates JWT authentication flow for SSH
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitJWTToken(self, request, context):
        """WaitJWTToken waits for JWT authentication completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCPUProfile(self, request, context):
        """StartCPUProfile starts CPU profiling in the daemon
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCPUProfile(self, request, context):
        """StopCPUProfile stops CPU profiling in the daemon
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstallerResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExposeService(self, request, context):
        """ExposeService exposes a local port via the NetBird reverse proxy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaemonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=daemon__pb2.LoginRequest.FromString,
                    response_serializer=daemon__pb2.LoginResponse.SerializeToString,
            ),
            'WaitSSOLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitSSOLogin,
                    request_deserializer=daemon__pb2.WaitSSOLoginRequest.FromString,
                    response_serializer=daemon__pb2.WaitSSOLoginResponse.SerializeToString,
            ),
            'Up': grpc.unary_unary_rpc_method_handler(
                    servicer.Up,
                    request_deserializer=daemon__pb2.UpRequest.FromString,
                    response_serializer=daemon__pb2.UpResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=daemon__pb2.StatusRequest.FromString,
                    response_serializer=daemon__pb2.StatusResponse.SerializeToString,
            ),
            'Down': grpc.unary_unary_rpc_method_handler(
                    servicer.Down,
                    request_deserializer=daemon__pb2.DownRequest.FromString,
                    response_serializer=daemon__pb2.DownResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=daemon__pb2.GetConfigRequest.FromString,
                    response_serializer=daemon__pb2.GetConfigResponse.SerializeToString,
            ),
            'ListNetworks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNetworks,
                    request_deserializer=daemon__pb2.ListNetworksRequest.FromString,
                    response_serializer=daemon__pb2.ListNetworksResponse.SerializeToString,
            ),
            'SelectNetworks': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectNetworks,
                    request_deserializer=daemon__pb2.SelectNetworksRequest.FromString,
                    response_serializer=daemon__pb2.SelectNetworksResponse.SerializeToString,
            ),
            'DeselectNetworks': grpc.unary_unary_rpc_method_handler(
                    servicer.DeselectNetworks,
                    request_deserializer=daemon__pb2.SelectNetworksRequest.FromString,
                    response_serializer=daemon__pb2.SelectNetworksResponse.SerializeToString,
            ),
            'ForwardingRules': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardingRules,
                    request_deserializer=daemon__pb2.EmptyRequest.FromString,
                    response_serializer=daemon__pb2.ForwardingRulesResponse.SerializeToString,
            ),
            'DebugBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.DebugBundle,
                    request_deserializer=daemon__pb2.DebugBundleRequest.FromString,
                    response_serializer=daemon__pb2.DebugBundleResponse.SerializeToString,
            ),
            'GetLogLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogLevel,
                    request_deserializer=daemon__pb2.GetLogLevelRequest.FromString,
                    response_serializer=daemon__pb2.GetLogLevelResponse.SerializeToString,
            ),
            'SetLogLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLogLevel,
                    request_deserializer=daemon__pb2.SetLogLevelRequest.FromString,
                    response_serializer=daemon__pb2.SetLogLevelResponse.SerializeToString,
            ),
            'ListStates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStates,
                    request_deserializer=daemon__pb2.ListStatesRequest.FromString,
                    response_serializer=daemon__pb2.ListStatesResponse.SerializeToString,
            ),
            'CleanState': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanState,
                    request_deserializer=daemon__pb2.CleanStateRequest.FromString,
                    response_serializer=daemon__pb2.CleanStateResponse.SerializeToString,
            ),
            'DeleteState': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteState,
                    request_deserializer=daemon__pb2.DeleteStateRequest.FromString,
                    response_serializer=daemon__pb2.DeleteStateResponse.SerializeToString,
            ),
            'SetSyncResponsePersistence': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSyncResponsePersistence,
                    request_deserializer=daemon__pb2.SetSyncResponsePersistenceRequest.FromString,
                    response_serializer=daemon__pb2.SetSyncResponsePersistenceResponse.SerializeToString,
            ),
            'TracePacket': grpc.unary_unary_rpc_method_handler(
                    servicer.TracePacket,
                    request_deserializer=daemon__pb2.TracePacketRequest.FromString,
                    response_serializer=daemon__pb2.TracePacketResponse.SerializeToString,
            ),
            'StartCapture': grpc.unary_stream_rpc_method_handler(
                    servicer.StartCapture,
                    request_deserializer=daemon__pb2.StartCaptureRequest.FromString,
                    response_serializer=daemon__pb2.CapturePacket.SerializeToString,
            ),
            'StartBundleCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBundleCapture,
                    request_deserializer=daemon__pb2.StartBundleCaptureRequest.FromString,
                    response_serializer=daemon__pb2.StartBundleCaptureResponse.SerializeToString,
            ),
            'StopBundleCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.StopBundleCapture,
                    request_deserializer=daemon__pb2.StopBundleCaptureRequest.FromString,
                    response_serializer=daemon__pb2.StopBundleCaptureResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=daemon__pb2.SubscribeRequest.FromString,
                    response_serializer=daemon__pb2.SystemEvent.SerializeToString,
            ),
            'GetEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=daemon__pb2.GetEventsRequest.FromString,
                    response_serializer=daemon__pb2.GetEventsResponse.SerializeToString,
            ),
            'SwitchProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchProfile,
                    request_deserializer=daemon__pb2.SwitchProfileRequest.FromString,
                    response_serializer=daemon__pb2.SwitchProfileResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=daemon__pb2.SetConfigRequest.FromString,
                    response_serializer=daemon__pb2.SetConfigResponse.SerializeToString,
            ),
            'AddProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProfile,
                    request_deserializer=daemon__pb2.AddProfileRequest.FromString,
                    response_serializer=daemon__pb2.AddProfileResponse.SerializeToString,
            ),
            'RenameProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameProfile,
                    request_deserializer=daemon__pb2.RenameProfileRequest.FromString,
                    response_serializer=daemon__pb2.RenameProfileResponse.SerializeToString,
            ),
            'RemoveProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProfile,
                    request_deserializer=daemon__pb2.RemoveProfileRequest.FromString,
                    response_serializer=daemon__pb2.RemoveProfileResponse.SerializeToString,
            ),
            'ListProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProfiles,
                    request_deserializer=daemon__pb2.ListProfilesRequest.FromString,
                    response_serializer=daemon__pb2.ListProfilesResponse.SerializeToString,
            ),
            'GetActiveProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveProfile,
                    request_deserializer=daemon__pb2.GetActiveProfileRequest.FromString,
                    response_serializer=daemon__pb2.GetActiveProfileResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=daemon__pb2.LogoutRequest.FromString,
                    response_serializer=daemon__pb2.LogoutResponse.SerializeToString,
            ),
            'GetFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatures,
                    request_deserializer=daemon__pb2.GetFeaturesRequest.FromString,
                    response_serializer=daemon__pb2.GetFeaturesResponse.SerializeToString,
            ),
            'TriggerUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerUpdate,
                    request_deserializer=daemon__pb2.TriggerUpdateRequest.FromString,
                    response_serializer=daemon__pb2.TriggerUpdateResponse.SerializeToString,
            ),
            'GetPeerSSHHostKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeerSSHHostKey,
                    request_deserializer=daemon__pb2.GetPeerSSHHostKeyRequest.FromString,
                    response_serializer=daemon__pb2.GetPeerSSHHostKeyResponse.SerializeToString,
            ),
            'RequestJWTAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestJWTAuth,
                    request_deserializer=daemon__pb2.RequestJWTAuthRequest.FromString,
                    response_serializer=daemon__pb2.RequestJWTAuthResponse.SerializeToString,
            ),
            'WaitJWTToken': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitJWTToken,
                    request_deserializer=daemon__pb2.WaitJWTTokenRequest.FromString,
                    response_serializer=daemon__pb2.WaitJWTTokenResponse.SerializeToString,
            ),
            'StartCPUProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCPUProfile,
                    request_deserializer=daemon__pb2.StartCPUProfileRequest.FromString,
                    response_serializer=daemon__pb2.StartCPUProfileResponse.SerializeToString,
            ),
            'StopCPUProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCPUProfile,
                    request_deserializer=daemon__pb2.StopCPUProfileRequest.FromString,
                    response_serializer=daemon__pb2.StopCPUProfileResponse.SerializeToString,
            ),
            'GetInstallerResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstallerResult,
                    request_deserializer=daemon__pb2.InstallerResultRequest.FromString,
                    response_serializer=daemon__pb2.InstallerResultResponse.SerializeToString,
            ),
            'ExposeService': grpc.unary_stream_rpc_method_handler(
                    servicer.ExposeService,
                    request_deserializer=daemon__pb2.ExposeServiceRequest.FromString,
                    response_serializer=daemon__pb2.ExposeServiceEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'daemon.DaemonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('daemon.DaemonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DaemonService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/Login',
            daemon__pb2.LoginRequest.SerializeToString,
            daemon__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitSSOLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/WaitSSOLogin',
            daemon__pb2.WaitSSOLoginRequest.SerializeToString,
            daemon__pb2.WaitSSOLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Up(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/Up',
            daemon__pb2.UpRequest.SerializeToString,
            daemon__pb2.UpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/Status',
            daemon__pb2.StatusRequest.SerializeToString,
            daemon__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Down(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/Down',
            daemon__pb2.DownRequest.SerializeToString,
            daemon__pb2.DownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/GetConfig',
            daemon__pb2.GetConfigRequest.SerializeToString,
            daemon__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNetworks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/ListNetworks',
            daemon__pb2.ListNetworksRequest.SerializeToString,
            daemon__pb2.ListNetworksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectNetworks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/SelectNetworks',
            daemon__pb2.SelectNetworksRequest.SerializeToString,
            daemon__pb2.SelectNetworksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeselectNetworks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/DeselectNetworks',
            daemon__pb2.SelectNetworksRequest.SerializeToString,
            daemon__pb2.SelectNetworksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardingRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/ForwardingRules',
            daemon__pb2.EmptyRequest.SerializeToString,
            daemon__pb2.ForwardingRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DebugBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/DebugBundle',
            daemon__pb2.DebugBundleRequest.SerializeToString,
            daemon__pb2.DebugBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/GetLogLevel',
            daemon__pb2.GetLogLevelRequest.SerializeToString,
            daemon__pb2.GetLogLevelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLogLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/SetLogLevel',
            daemon__pb2.SetLogLevelRequest.SerializeToString,
            daemon__pb2.SetLogLevelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/ListStates',
            daemon__pb2.ListStatesRequest.SerializeToString,
            daemon__pb2.ListStatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/CleanState',
            daemon__pb2.CleanStateRequest.SerializeToString,
            daemon__pb2.CleanStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/DeleteState',
            daemon__pb2.DeleteStateRequest.SerializeToString,
            daemon__pb2.DeleteStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSyncResponsePersistence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/SetSyncResponsePersistence',
            daemon__pb2.SetSyncResponsePersistenceRequest.SerializeToString,
            daemon__pb2.SetSyncResponsePersistenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TracePacket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/TracePacket',
            daemon__pb2.TracePacketRequest.SerializeToString,
            daemon__pb2.TracePacketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.DaemonService/StartCapture',
            daemon__pb2.StartCaptureRequest.SerializeToString,
            daemon__pb2.CapturePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartBundleCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/StartBundleCapture',
            daemon__pb2.StartBundleCaptureRequest.SerializeToString,
            daemon__pb2.StartBundleCaptureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopBundleCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/StopBundleCapture',
            daemon__pb2.StopBundleCaptureRequest.SerializeToString,
            daemon__pb2.StopBundleCaptureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.DaemonService/SubscribeEvents',
            daemon__pb2.SubscribeRequest.SerializeToString,
            daemon__pb2.SystemEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/GetEvents',
            daemon__pb2.GetEventsRequest.SerializeToString,
            daemon__pb2.GetEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/SwitchProfile',
            daemon__pb2.SwitchProfileRequest.SerializeToString,
            daemon__pb2.SwitchProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/SetConfig',
            daemon__pb2.SetConfigRequest.SerializeToString,
            daemon__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/AddProfile',
            daemon__pb2.AddProfileRequest.SerializeToString,
            daemon__pb2.AddProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/RenameProfile',
            daemon__pb2.RenameProfileRequest.SerializeToString,
            daemon__pb2.RenameProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/RemoveProfile',
            daemon__pb2.RemoveProfileRequest.SerializeToString,
            daemon__pb2.RemoveProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/ListProfiles',
            daemon__pb2.ListProfilesRequest.SerializeToString,
            daemon__pb2.ListProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/GetActiveProfile',
            daemon__pb2.GetActiveProfileRequest.SerializeToString,
            daemon__pb2.GetActiveProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/Logout',
            daemon__pb2.LogoutRequest.SerializeToString,
            daemon__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/GetFeatures',
            daemon__pb2.GetFeaturesRequest.SerializeToString,
            daemon__pb2.GetFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/TriggerUpdate',
            daemon__pb2.TriggerUpdateRequest.SerializeToString,
            daemon__pb2.TriggerUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeerSSHHostKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/GetPeerSSHHostKey',
            daemon__pb2.GetPeerSSHHostKeyRequest.SerializeToString,
            daemon__pb2.GetPeerSSHHostKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestJWTAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/RequestJWTAuth',
            daemon__pb2.RequestJWTAuthRequest.SerializeToString,
            daemon__pb2.RequestJWTAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitJWTToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/WaitJWTToken',
            daemon__pb2.WaitJWTTokenRequest.SerializeToString,
            daemon__pb2.WaitJWTTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartCPUProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/StartCPUProfile',
            daemon__pb2.StartCPUProfileRequest.SerializeToString,
            daemon__pb2.StartCPUProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCPUProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/StopCPUProfile',
            daemon__pb2.StopCPUProfileRequest.SerializeToString,
            daemon__pb2.StopCPUProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstallerResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.DaemonService/GetInstallerResult',
            daemon__pb2.InstallerResultRequest.SerializeToString,
            daemon__pb2.InstallerResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExposeService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.DaemonService/ExposeService',
            daemon__pb2.ExposeServiceRequest.SerializeToString,
            daemon__pb2.ExposeServiceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
